import Navbar from "@/components/Navbar"
import Head from "next/head"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rick | Front-End Developer</title>
        <meta name="My portfolio website built in next" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />


    </div>
  )
}
